[project]
name = "pyproject"
version = "0.1.0"
description = "ML_Tools"
authors = [
    {name = "Rhys Wells"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "Y"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
