OPENDOTA_BASE_PATH = "https://api.opendota.com/api"

ENDPOINT_GET_PRO_PLAYER_LIST = OPENDOTA_BASE_PATH + "/proPlayers"
ENDPOINT_GET_PLAYER_INFO = OPENDOTA_BASE_PATH + "/players/{}"
ENDPOINT_GET_PRO_TEAM_LIST = OPENDOTA_BASE_PATH + "/teams"
ENDPOINT_GET_PRO_TEAM_PLAYER_LIST = OPENDOTA_BASE_PATH + "/teams/{}/players"
ENDPOINT_GET_PLAYER_MMR_DISTRIBUTION = OPENDOTA_BASE_PATH + "/distributions"
