name: Generate Markdown Table

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas pyyaml google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Generate Markdown Table
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GOOGLE_CREDENTIALS}" > google_creds.json
          python .github/scripts/generate_table.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Data-Archive-Link-Table.md
          git commit -m "Auto-update summary table" || echo "No changes to commit"
          git push
